# Uprating

As part of the data generation process, we uprate the 2015 PUF to match 2021 SOI statistics. The table below shows all variables which are uprated *directly* from SOI aggregates.

In [30]:
import pandas as pd
from tax_microdata_benchmarking.storage import STORAGE_FOLDER
from microdf import MicroDataFrame
from tax_microdata_benchmarking.datasets.uprate_puf import (
    SOI_TO_PUF_STRAIGHT_RENAMES,
    SOI_TO_PUF_NEG_ONLY_RENAMES,
    SOI_TO_PUF_POS_ONLY_RENAMES,
)

# Set maximum number of columns to display in pandas output to infinite
pd.set_option("display.max_columns", None)

puf_2015 = pd.read_csv(STORAGE_FOLDER / "input" / "puf_2015.csv")
puf_2021 = pd.read_csv(STORAGE_FOLDER / "output" / "puf_2021.csv")

puf_2015.S006 /= 100
puf_2021.S006 /= 100
puf_2015 = MicroDataFrame(puf_2015, weights="S006")
puf_2021 = MicroDataFrame(puf_2021, weights="S006")

totals_2015 = puf_2015.sum()
totals_2021 = puf_2021.sum()

uprating_df = pd.DataFrame()
uprating_df["2015 total ($bn)"] = (puf_2015.sum() / 1e9).round(1)
uprating_df["2021 total ($bn)"] = (puf_2021.sum() / 1e9).round(1)
uprating_df["Growth (%)"] = ((totals_2021 / totals_2015 - 1) * 100).round(1)
# uprating_df["Annualised growth (%)"] = (((totals_2021 / totals_2015) ** (1 / (2021 - 2015)) - 1) * 100).round(1)

UPRATED_DIRECTLY_FROM_SOI = list(
    list(SOI_TO_PUF_STRAIGHT_RENAMES.values())
    + list(SOI_TO_PUF_NEG_ONLY_RENAMES.values())
    + list(SOI_TO_PUF_POS_ONLY_RENAMES.values())
)

uprating_df.T[UPRATED_DIRECTLY_FROM_SOI].T.sort_values("Growth (%)").T

,E18500,E19200,E26270,E26270,E18400,E18400,E17500,E00400,E00300,E19800,E01700,E00200,E01500,E02400,E00650,E00600,E02500,E01400,E00900,E00900,E01100,E01000,E01000,E02300
2015 total ($bn),188.9,306.6,633.1,633.1,352.8,352.8,132.1,61.6,97.8,163.5,693.0,7156.3,1178.9,604.8,204.0,260.9,277.0,251.8,332.4,332.4,11.8,701.4,701.4,26.7
2021 total ($bn),100.1,164.4,419.9,419.9,254.2,254.2,100.6,55.3,105.7,194.0,861.8,9078.3,1519.6,790.7,297.1,388.0,412.2,406.1,560.2,560.2,24.3,2051.5,2051.5,204.6
Growth (%),-47.0,-46.4,-33.7,-33.7,-28.0,-28.0,-23.9,-10.3,8.0,18.7,24.4,26.9,28.9,30.7,45.6,48.7,48.8,61.3,68.5,68.5,106.6,192.5,192.5,667.2